services:
  app:
    build: .
    ports:
      - "621:3000"
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
