services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
